### ISSUE TITLE
CRD for koji-hub

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/mbbox#10]
As part of the work on mbbox operator, we should create [CRD](https://docs.openshift.com/container-platform/4.3/operators/crds/crd-extending-api-with-crds.html) for [koji-hub component](https://github.com/fedora-infra/mbbox/tree/master/components/koji_hub).

**Comment by sfinn85** [comment]
**Acceptance Criteria **

- To have complete custom requirements definition 
- For the Koji hub to deploy and use it in the operator 

**DOD**

- Acceptance Criteria is met 
- Team member review/approval
- Local tests have been run and pass - if failed it is re-opened/fixed and passed
