### ISSUE TITLE
CRD for koji-builder

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/mbbox#11]
As part of the work on mbbox operator, we should create [CRD](https://docs.openshift.com/container-platform/4.3/operators/crds/crd-extending-api-with-crds.html) for [koji-builder component](https://github.com/fedora-infra/mbbox/tree/master/components/koji_builder).

**Comment by Zlopez** [comment]
## Acceptance Criteria
* To have complete custom requirements definition for the Koji builder to deploy and use it in the operator

## Definition of Done
* Acceptance Criteria is met
* Team member review/approval
* Local tests have been run and pass - if failed it is re-opened/fixed and passed

**Comment by sfinn85** [comment]
Subtasks created:

- https://github.com/fedora-infra/mbbox/issues/32
- https://github.com/fedora-infra/mbbox/issues/30

There maybe more issues created based on integration.

**Comment by Zlopez** [comment]
Currently blocked by #59

**Comment by Zlopez** [comment]
#20 is merged, we still didn't solve the issue with koji-hub and to let the test pass we commented out part of the cluster tests.
