### ISSUE TITLE
mbox-operator test-cluster job

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#22]
This PR creates the basic structure for running tests in a remote cluster: https://github.com/fedora-infra/mbbox/pull/21

It would be useful to have a CI job to run those tests (once developed) on every PR submission and even nightly jobs.

## Acceptance Criteria
* CI in place
* Automatic run for PRs
* Deployment of the Kubernetes (Openshift) in CI
* Local tests execution in CI

## Definition of Done
* Acceptance Criteria is met
* Run of the local tests in CI on at least one PR

**Comment by Zlopez** [comment]
After some discussion, we decided to go with Zuul.
