### ISSUE TITLE
koji-hub image

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#27]
As an User, I want to be able to pull koji-hub copntainer image from a public registry.

## Acceptance criteria

* Add a Dockerfile and related files to build a koji-hub container image;
* Host it in `quay.io/fedora/koji-hub:latest` (using latest tag for now);
* Setup automatic image building (we could use quay.io for that)..

## Definition of Done

The following image should be available and up-to-date: `quay.io/fedora/koji-hub:latest`

## Notes

* Check if quay.io auto build system can be used for the CI/CF bits.

**Comment by Zlopez** [comment]
I tried to play a bit with the `quay.io` with [koji-builder](https://quay.io/repository/fedora/koji-builder?tab=tags), but didn't find a way to add latest tag automatically. In the end I added it manually.

**Comment by odra** [comment]
Merged in #19
