### ISSUE TITLE
koji-hub crd documentation

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#28]
As an User, I want to know which properties can be set in the koji-hub CR.

## Acceptance Criteria

* A `docs` folder in the root project dir containing a README file on the CRD usage;
* Document each property name, value type and  short description on its purpose.

## Definition of Done

Sphinx html docs that contain the explanation of this custom resource and its properties.

**Comment by Zlopez** [comment]
I think we should aim for [ReadTheDocs](https://readthedocs.org/) documentation instead of just README.

**Comment by Zlopez** [comment]
I created a #31 for it. I think it will be nice to have it.
