### ISSUE TITLE
mbox crd

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#33]
As an User, I want one mbox CR to handle all mbox CRDs for me.

## Acceptance Criteria

* manage root CA secret - create one if it is not present
* manage shared koji PVC for both koji-builder and koji-hub: includes name and pvc size
* manage shared postgresql instance for testing
* manage shared config for mbs-frontend and mbs-backend
* change koji-hub and koji-builder to not  create root CA and PVC resources - they should fail in case those are missing
* Update docs with regards to this CRD usage

## Definitioin of Done

Mbox CR documentation and managing shared resources between koji-hub and koji-builder.

**Comment by Zlopez** [comment]
We are still missing documentation for mbox shared CRD
