### ISSUE TITLE
Refactor molecule test-suites to share test-cases

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/mbbox#52]
Currently `molecule test -s test-local` runs more asserts than `molecule test -s test cluster`.

The `molecule test -s test-local` is easier for developer to run locally, as it creates its own cluster to deploy into (through kind project)

The `molecule test -s test cluster` can run against arbitrary cluster, and is running in our CI, but the tests are not there yet. 

# Acceptance criteria
* bootstraping of the environment is flexible (i.e. spawning a cluster with `kind` or running against external cluster)
* we have base battery of test-cases that can be shared regardless of the environment

# Definition of Done

* Running of either of `test-local` and `test-cluster` results in running same deployments and asserts
* Somebody from the team reviewed the changes
* The tests won't be merged before there is a succesful run for both `test-local` and `test-cluster`

# Notes

There is some work done in this regard by @Zlopez in his PR #20 
There might be more refactoring requred after that part of work is merged.

**Comment by sfinn85** [comment]
8 story points

**Comment by sfinn85** [comment]
Hi @AdamSaleh 

Just on sprint 3 review call.

Can we get an update on this to let us know if its done or if we have work remaining.

Thanks a mill

Sarah
