### ISSUE TITLE
Identity Container Image

### ISSUE THREAD

**Issue by odra** [fedora-infra/mbbox#54]
As a Developer, I want an identity(ipsilon) container image and kubernetes resource files to use in my operator development environment

## Acceptance Criteria

* A Dockerfile that builds an ipsilon image with a start script;
* Kubernetes resource files (configmaps, deployment, services, pvcs, etc);
* Image pushed to `quay.io/fedora`

## Definition of Done

Being able to deploy idenity (ipsilon) in kubernetes.

**Comment by James6xie** [comment]
Hi man !!!

docker pull quay.io/fedora/identity
Using default tag: latest
Error response from daemon: unauthorized: access to the requested resource is not authorized


while deploy mbbox on my k8s env, said i can not access the mirrors quay.io/fedora/identity, maybe is not a public mirrors . 

who can tell me how to pull it ?  

 Thanks a lot !!!!

**Comment by Zlopez** [comment]
@odra I don't see the identity container in fedora group on quay.io. Could you check it?

**Comment by odra** [comment]
I don't think you need that container image to deploy MBBOX.

We only support SSL based auth for now, that container image is not used anywhere.

**Comment by James6xie** [comment]
> I don't think you need that container image to deploy MBBOX.
> 
> We only support SSL based auth for now, that container image is not used anywhere.

OK,  I know, for me. olny want to build module-package myself. but there is not a simple method can do it . I had fall in mbs a long time . is there any good ways to do this ? you know koji can be deployed easy for all dist, but mbs not , it is vary hard now.

**Comment by Zlopez** [comment]
If you just want a running container, it shouldn't be a problem to build it form Dockerfile in MBBox. You just need to build both [backend](https://github.com/fedora-infra/mbbox/tree/master/images/mbs-backend) and [frontend](https://github.com/fedora-infra/mbbox/tree/master/images/mbs-frontend) and play with the configuration.

**Comment by James6xie** [comment]
nope  , for me mbs configure is a problem , not install rpms. 
i had mannuly installed [mbs-backend](https://github.com/fedora-infra/mbbox/blob/master/images/mbs-backend/Dockerfile) [mbs-frontend](https://github.com/fedora-infra/mbbox/blob/master/images/mbs-frontend/Dockerfile) on fedora33, and write mbs.configmap  but it is not work for me.  return message like  https://paste.centos.org/view/c7813546

**Comment by Zlopez** [comment]
In this case I would recommend to try asking directly on MBS https://pagure.io/fm-orchestrator I'm not sure if your configuration will work for you, also the MBS needs koji deployed to work.

**Comment by James6xie** [comment]
> In this case I would recommend to try asking directly on MBS https://pagure.io/fm-orchestrator I'm not sure if your configuration will work for you, also the MBS needs koji deployed to work.


OK, Thank you !!!
