### ISSUE TITLE
Get staging environment for deployment of the operator available 

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/mbbox#55]
As an Developer, I want to have a production-grade staging environment available for deployment and testing of mbbox operator 

## Acceptance criteria

* There is a publicly accessible kubernetes environment available, with access for at least @AdamSaleh @Zlopez and @odra 
* We have permissions to create the necessary CRDs and actually deploy and update the operator on the cluster 

## Definition of Done

There exists a kubernetes project/namespace where the operator is running.
The deployment doesn't actually have to work, it is only necessary to have the environment to do that.

## Notes

**Comment by bstinsonmhk** [comment]
I hear that we're looking for a production-like deployment of Openshift for testing purposes. Can we talk a little bit about requirements? That will help us get on the right infrastructure.

In IRC it was mentioned that we may need a cluster and cluster-admin permissions to make this happen.

**Comment by AdamSaleh** [comment]
@bstinsonmhk  when you look at our make-file, we are:

* creating and updating custom resource definitions
* creating a custom resource
* creating a service account with custom roles and role-bindings

This means we will need the cluster-admin permissions.

On the other hand, it looks like a smaller cluster could be enough, as we are currently developing/testing locally with mini-cube and it doesn't seem to be too taxing on our resources.

**Comment by AdamSaleh** [comment]
Waiting @bstinsonmhk to have time, as this is currently not time-sensitive or blocking us with work.

We still would like it within week or two :-)

**Comment by sfinn85** [comment]
Hi @bstinsonmhk 
Any updates on when you will have capacity to do this or anyone else on the CentOS team? This will help you review the guys work and give feedback to let us know if we need to carry out other work or re work

**Comment by sfinn85** [comment]
FYI @Zlopez @AdamSaleh @odra 

I caught up with @bstinsonmhk today. 

"Hi Brian, just wanted to follow regarding the staging environment for Mbbox, the team will need this no later than 6/10/20 to allow them complete the requirements for this initiative. If this is not possible we need to look at creating an alternative staging environment to test in this sprint. Can you let me know if is possible for you to complete by this time? If not, we can totally look into an alternative. "

Brian reverted back that it was a OK deadline and they should have completed by then. I asked Brian to create a ticket to allow us see progress without having to ping him. 

Lets all check in on 6/3/20 to see how this is going, I popped a call in the calendar

**Comment by sfinn85** [comment]
https://projects.engineering.redhat.com/browse/CPE-731 CI team working on this week - approx delivery date 6/10/20

**Comment by sfinn85** [comment]
HI @Zlopez @AdamSaleh @odra 
@bstinsonmhk Flagged that the staging environment has been created. Can you check this out?

**Comment by Zlopez** [comment]
@sfinn85 
We are currently communicating with Centos CI team to have our accounts ready to use. I think all of us will have access to the staging environment later this day when we solve the last remaining access issues :-)

**Comment by Zlopez** [comment]
We got the staging environment and we can now work in it.
