### ISSUE TITLE
Test the operator in staging environment

### ISSUE THREAD

**Issue by AdamSaleh** [fedora-infra/mbbox#96]
## Acceptance Criteria

1. have a staging environment at hand
2. run the operator deployment with `make deploy`
3. verify the deployment finished successfully
4. verify all the expected pods are running (not stuck, crashlooping, e.t.c)
5. verify none of the pods have unexpected errors
6. Document the deployment process

## Definition of Done

* We don't need to perform any E2E testing, according to @bstinsonmhk, deployment without errors should be enough

**Comment by Zlopez** [comment]
We are currently trying to solve the issue when deploying postgres in staging environment.

It looks like pods don't have permissions to change anything in PV, even if it's set to Read/Write mode.

**Comment by Zlopez** [comment]
Postgres issue was resolved today.

**Comment by Zlopez** [comment]
The staging environment could be found here: https://console-openshift-console.apps.ocp.stg.ci.centos.org/k8s/ns/mbbox
